"""add position events and snapshots

Revision ID: c89f7f098ca4
Revises: 02dc418a3eeb
Create Date: 2025-10-22 05:36:58.065055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89f7f098ca4'
down_revision: Union[str, Sequence[str], None] = '02dc418a3eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('logic_reason', sa.String(length=32), nullable=True),
    sa.Column("realized_pnl", sa.Float(), nullable=False, server_default="0"),

    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_events_group_id'), 'position_events', ['group_id'], unique=False)
    op.create_table('stats_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_open', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('logic1_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('logic2_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('logic3_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('logic4_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('logic5_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('raw_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_snapshots_snapshot_date'), 'stats_snapshots', ['snapshot_date'], unique=False)
    op.add_column('position_groups', sa.Column('realized_pnl', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('position_groups', 'realized_pnl', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_groups', 'realized_pnl')
    op.drop_index(op.f('ix_stats_snapshots_snapshot_date'), table_name='stats_snapshots')
    op.drop_table('stats_snapshots')
    op.drop_index(op.f('ix_position_events_group_id'), table_name='position_events')
    op.drop_table('position_events')
    op.alter_column("position_groups", "realized_pnl", server_default=None)

    # ### end Alembic commands ###
